branches:
  only:
  - master
sudo: required
services:
  - docker
before_install:
  - docker pull openaddr/prereqs:`cut -f1 -d. openaddr/VERSION`.x || true
  - docker build -f Dockerfile-prereqs -t openaddr/prereqs:`cut -f1 -d. openaddr/VERSION`.x .
  - docker build -f Dockerfile-machine -t openaddr/machine:`cut -f1 -d. openaddr/VERSION`.x .
script:
  # Postgres needs a little time
  - docker-compose up -d && sleep 15
  - docker-compose run machine python3 /usr/local/src/openaddr/test.py
