machine:
  image: openaddr/machine:7
  environment:
    - DATABASE_URL=postgresql://openaddr:openaddr@postgres/openaddr
  links:
    - postgres
  volumes:
    - .:/vol
postgres:
  image: mdillon/postgis:9.5
  environment:
    - POSTGRES_USER=openaddr
    - POSTGRES_PASSWORD=openaddr
