version: 2
jobs:

  # Prepare Docker images for use in Release step.
  # Optimistically prepares images in parallel with Test step.
  Build:
    machine: true
    steps:
      - checkout
      - run: .circleci/prepare-docker-images.sh

      # Save images, but don't perform tests
      - run: docker save openaddr/prereqs:`cat /tmp/P/MAJOR` $(docker history -q openaddr/prereqs:`cat /tmp/P/MAJOR` | grep -v missing) | gzip -c --fast > /tmp/P/prereqs.gz
      - run: docker save openaddr/machine:`cat /tmp/P/MAJOR` | gzip -c --fast > /tmp/P/machine.gz
      - persist_to_workspace:
          root: /tmp/P
          paths:
            - FULL
            - MAJOR
            - prereqs.gz
            - machine.gz

  # Run tests inside prepared Docker container.
  Test:
    machine: true
    steps:
      - checkout
      - run: .circleci/prepare-docker-images.sh

      # Perform tests, but don't keep images around
      - run: docker-compose up -d && sleep 15
      - run: docker-compose run machine python3 /usr/local/src/openaddr/test.py

  # Package Docker images and upload to S3 for use in production.
  Package:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/P
      - run: mkdir -p /tmp/images
      - run: cp /tmp/P/prereqs.gz /tmp/images/openaddr-prereqs-`cat /tmp/P/MAJOR`.tar.gz
      - run: cp /tmp/P/machine.gz /tmp/images/openaddr-machine-`cat /tmp/P/MAJOR`.tar.gz
      - run: gunzip -c /tmp/P/machine.gz | docker load
      - run: docker tag openaddr/machine:`cat /tmp/P/MAJOR` openaddr/machine:`cat /tmp/P/FULL`
      - run: docker save openaddr/machine:`cat /tmp/P/FULL` | gzip -c --fast > /tmp/images/openaddr-machine-`cat /tmp/P/FULL`.tar.gz
      - run: aws s3 cp --quiet --recursive --acl public-read /tmp/images/ s3://data.openaddresses.io/docker/

  # Deploy new version of Machine to EC2 and Lambda
  Deploy:
    docker:
      - image: circleci/python:3.5-jessie-browsers
    steps:
      - checkout
      - run: pip3 install --user boto3
      - run: ops/update-scheduled-tasks.py
      - run: ops/update-webhooks-group.py

workflows:
  version: 2
  everything:
    jobs:
      - Test
      - Build:
          filters:
            branches:
              only: 7.x
      - Package:
          requires:
            - Build
            - Test
          filters:
            branches:
              only: 7.x
      - Deploy:
          requires:
            - Package
          filters:
            branches:
              only: 7.x
